name: Update README with Organization stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  Collect-stats:
    runs-on: ubuntu-latest

    name: Collect stats

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Get ORG stats
        uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: Insights-Tech
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Write stats to csv file
        uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/octokit.csv
          columns: open issues,closed issues,open pull requests,closed pull requests,merged pull requests
          "open issues": ${{ fromJson(steps.stats.outputs.data).openIssues }}
          "closed issues": ${{ fromJson(steps.stats.outputs.data).closedIssues }}
          "open pull requests": ${{ fromJson(steps.stats.outputs.data).openPullRequests }}
          "closed pull requests": ${{ fromJson(steps.stats.outputs.data).closedPullRequests }}
          "merged pull requests": ${{ fromJson(steps.stats.outputs.data).mergedPullRequests }}
      
      - name: Output stats
        run: |
          cat data/octokit.csv