name: Update README with Organization stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  Collect-stats:
    runs-on: ubuntu-latest

    name: Collect stats

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: Insights-Tech
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cat << EOF
          result: ${{ steps.stats.outputs.data }}
          EOF
